source 'https://rubygems.org'
ruby '2.3.1'
gem 'rails', '4.2.6'
gem 'pg'
gem 'puma'
gem 'mini_racer'
gem 'sassc-rails', github: 'sass/sassc-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'haml'
gem 'haml-rails'
gem 'html_truncator'
gem 'bootstrap-sass'
gem 'carrierwave'
gem 'mini_magick'
gem 'rack-wwwhisper', '~> 1.0'
gem 'rack-cache'
gem 'redis'
gem 'redis-rails', github: 'redis-store/redis-rails'
gem 'redis-rack-cache', github: 'redis-store/redis-rack-cache'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'rails_12factor'
gem 'friendly_id'
gem 'activeadmin', github: 'activeadmin'
gem 'devise'
gem 'devise-async'
gem 'cancan'
gem 'draper'
gem 'pundit'
gem 'sinatra', :require => false
gem 'geocoder'
gem 'country_select'
gem 'gon'
gem "autoprefixer-rails"

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'foreman'
end
